name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
        java-version: 1.8
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 18.16.0
    - name: Install Puppeteer
      run: npm install puppeteer
    - name: Install Chrome
      run: npx puppeteer browsers install chrome
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run generative tests
      run: lein test :generative
    - name: Run recent-clj tests
      run: lein with-profile dev,recent-clj test
    - name: Run clj-kondo linter
      run: lein with-profile dev,recent-clj clj-kondo-lint
